version: "3"
name: "bpmn-assignments-api"
services:
  mssql-server:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server
    environment:
      TZ: "America/Sao_Paulo"
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "My@P@ss2022W0rd"
      MSSQL_AGENT_ENABLED: true
    volumes:
      - mssql:/var/opt/mssql
    ports:
      - "1433:1433"
    restart: always
  bpmn-api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "America/Sao_Paulo"
      DbServer: "mssql-server"
      DbUser: "SA"
      Password: "My@P@ss2022W0rd"
      Database: "BpmnAssignments"
    volumes:
      - apilogs:/logs
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mssql-server
volumes:
  mssql:
    name: "mssql"
  apilogs:
    name: "apilogs"