apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out kubernetes-kompose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: bpmn-api
      name: bpmn-api
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: bpmn-api
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out kubernetes-kompose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mssql-server
      name: mssql-server
    spec:
      ports:
        - name: "1433"
          port: 1433
          targetPort: 1433
      selector:
        io.kompose.service: mssql-server
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out kubernetes-kompose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: bpmn-api
      name: bpmn-api
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: bpmn-api
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out kubernetes-kompose.yaml
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.service: bpmn-api
        spec:
          containers:
            - env:
                - name: Database
                  value: BpmnAssignments
                - name: DbServer
                  value: mssql-server
                - name: DbUser
                  value: SA
                - name: Password
                  value: My@P@ss2022W0rd
                - name: TZ
                  value: America/Sao_Paulo
              image: bpmn-api
              name: api
              ports:
                - containerPort: 80
              resources: {}
              volumeMounts:
                - mountPath: /logs
                  name: apilogs
          restartPolicy: Always
          volumes:
            - name: apilogs
              persistentVolumeClaim:
                claimName: apilogs
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apilogs
      name: apilogs
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out kubernetes-kompose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mssql-server
      name: mssql-server
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: mssql-server
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert --out kubernetes-kompose.yaml
            kompose.version: 1.26.1 (a9d05d509)
          creationTimestamp: null
          labels:
            io.kompose.service: mssql-server
        spec:
          containers:
            - env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: MSSQL_AGENT_ENABLED
                  value: "true"
                - name: SA_PASSWORD
                  value: My@P@ss2022W0rd
                - name: TZ
                  value: America/Sao_Paulo
              image: mcr.microsoft.com/mssql/server
              name: mssql-server
              ports:
                - containerPort: 1433
              resources: {}
              volumeMounts:
                - mountPath: /var/opt/mssql
                  name: mssql
          restartPolicy: Always
          volumes:
            - name: mssql
              persistentVolumeClaim:
                claimName: mssql
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mssql
      name: mssql
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
kind: List
metadata: {}

